const fs = require('fs')
const p = 'src/services/ContentService.ts'
let s = ''
s += 'import { contentRepository } from "@/repositories/ContentRepository"\n'
s += 'import { projectRepository } from "@/repositories/ProjectRepository"\n'
s += 'import { NotFoundError, ValidationError } from "@/lib/errors"\n'
s += 'import { auditLogService } from "./AuditLogService"\n'
s += 'import { isAiEnabled, getAiProvider } from "@/config/ai"\n'
s += 'import type { KeywordIntent } from "@/constants"\n\n'
s += 'type OrgUser = { id: string; organization_id: string }\n\n'
s += 'export class ContentService {\n'
s += '  async getAuthorizedProject(projectId: string, user: OrgUser) {\n'
s += '    const project = await projectRepository.findByPkWithOrganization(projectId)\n'
s += '    if (!project || project.organization_id !== user.organization_id) {\n'
s += '      throw new NotFoundError("Project not found")\n'
s += '    }\n'
s += '    return project\n'
s += '  }\n\n'
s += '  private generateSlug(title: string): string {\n'
s += '    return title.toLowerCase().trim().replace(/[^\\w\\s-]/g, "").replace(/[\\s_-]+/g, "-").replace(/^-+|-+$/g, "")\n'
s += '  }\n\n'
s += '  // ============================ Content Briefs ============================\n\n'
s += '  async createContentBrief(\n'
s += '    user: OrgUser,\n'
s += '    projectId: string,\n'
s += '    createData: {\n'
s += '      keyword: string\n'
s += '      search_intent?: KeywordIntent | null\n'
s += '      suggested_title?: string | null\n'
s += '      outline?: unknown\n'
s += '      competitor_urls?: string[] | null\n'
s += '      related_keywords?: string[] | null\n'
s += '      questions?: string[] | null\n'
s += '    },\n'
s += '  ) {\n'
s += '    const project = await this.getAuthorizedProject(projectId, user)\n\n'
s += '    const brief = await contentRepository.createBrief({\n'
s += '      project_id: project.id,\n'
s += '      keyword: createData.keyword,\n'
s += '      search_intent: createData.search_intent ?? null,\n'
s += '      suggested_title: createData.suggested_title ?? null,\n'
s += '      outline: createData.outline ?? null,\n'
s += '      competitor_urls: createData.competitor_urls ?? null,\n'
s += '      related_keywords: createData.related_keywords ?? null,\n'
s += '      questions: createData.questions ?? null,\n'
s += '    })\n\n'
s += '    await auditLogService.log(user.organization_id, user.id, "content_brief.created", brief.id, {\n'
s += '      keyword: brief.keyword,\n'
s += '      project_id: project.id,\n'
s += '    })\n\n'
s += '    return brief\n'
s += '  }\n\n'
s += '  async getContentBrief(user: OrgUser, briefId: string) {\n'
s += '    const brief = await contentRepository.findBriefById(briefId)\n'
s += '    if (!brief) throw new NotFoundError("Content brief not found")\n'
s += '    return brief\n'
s += '  }\n\n'
s += '  async listContentBriefs(\n'
s += '    user: OrgUser,\n'
s += '    options?: {\n'
s += '      page?: number\n'
s += '      limit?: number\n'
s += '      keyword?: string\n'
s += '    },\n'
s += '  ) {\n'
s += '    return contentRepository.findBriefsByOrganizationPaginated(user.organization_id, {\n'
s += '      page: options?.page ?? 1,\n'
s += '      pageSize: options?.limit ?? 20,\n'
s += '      keyword: options?.keyword,\n'
s += '    })\n'
s += '  }\n\n'
s += '  async updateContentBrief(\n'
s += '    user: OrgUser,\n'
s += '    briefId: string,\n'
s += '    updates: {\n'
s += '      keyword?: string\n'
s += '      search_intent?: KeywordIntent | null\n'
s += '      suggested_title?: string | null\n'
s += '      outline?: unknown\n'
s += '      competitor_urls?: string[] | null\n'
s += '      related_keywords?: string[] | null\n'
s += '      questions?: string[] | null\n'
s += '    },\n'
s += '  ) {\n'
s += '    const brief = await contentRepository.findBriefById(briefId)\n'
s += '    if (!brief) throw new NotFoundError("Content brief not found")\n\n'
s += '    await brief.update({\n'
s += '      ...(updates.keyword !== undefined && { keyword: updates.keyword }),\n'
s += '      ...(updates.search_intent !== undefined && { search_intent: updates.search_intent }),\n'
s += '      ...(updates.suggested_title !== undefined && { suggested_title: updates.suggested_title }),\n'
s += '      ...(updates.outline !== undefined && { outline: updates.outline }),\n'
s += '      ...(updates.competitor_urls !== undefined && { competitor_urls: updates.competitor_urls }),\n'
s += '      ...(updates.related_keywords !== undefined && { related_keywords: updates.related_keywords }),\n'
s += '      ...(updates.questions !== undefined && { questions: updates.questions }),\n'
s += '    })\n\n'
s += '    await auditLogService.log(user.organization_id, user.id, "content_brief.updated", briefId, {\n'
s += '      keyword: brief.keyword,\n'
s += '    })\n\n'
s += '    return brief\n'
s += '  }\n\n'
s += '  async deleteContentBrief(user: OrgUser, briefId: string, projectId: string) {\n'
s += '    const brief = await contentRepository.findBriefByProjectAndId(projectId, briefId)\n'
s += '    if (!brief) throw new NotFoundError("Content brief not found")\n'
s += '    const deleted = await contentRepository.deleteBrief(briefId, projectId)\n'
s += '    if (deleted === 0) throw new NotFoundError("Content brief not found")\n'
s += '    await auditLogService.log(user.organization_id, user.id, "content_brief.deleted", briefId, {})\n'
s += '    return { success: true }\n'
s += '  }\n'
s += '}\n'
fs.writeFileSync(p, s)
console.log('part1 ok', s.length, 'chars')
